version: '3'
services:
  dbtest:
    image: mysql:latest
    container_name: dbtest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbtest
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command: --max_connections=500

  phpmyadmins:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmins
    environment:
      PMA_HOST: dbtest
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - dbtest
volumes:
  my-datavolume:
